project_name: flog

builds:
  - id: cli
    binary: flog
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: archive
    builds:
      - cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - Update README.md
      - Merge pull request
      - Merge branch